'use strict';
var diseaseToArrayML = {
    "Arthritis": [/Arthritis/],
    "Small bowel obstruction - closed loop or ischemia": [/Small bowel obstruction - closed loop or ischemia/],
    "Subarachnoid hemorrhage with aneurysm": [/Subarachnoid hemorrhage with aneurysm/],
    "Liver lesions": [/Liver lesions/],
    "Metastatic thyroid uptake": [/Metastatic thyroid uptake/],
    "Esophageal atresia": [/Esophageal atresia/],
    "Pulmonary embolism": [/Pulmonary embolism/],
    "Ovarian or Testicular torsion": [/Ovarian or Testicular torsion/],
    "Testicular torsion": [/Testicular torsion/],
    "Bone metastases": [/Bone metastases/],
    "Pneumothorax": [/Pneumothorax/],
    "Decreased GB EF": [/Decreased GB EF/],
    "Solid organ injury": [/Solid organ injury/],
    "Dysmotility": [/Dysmotility/],
    "Intracranial hemorrhage": [/Intracranial hemorrhage/],
    "Pulmonary alveolar proteinosis": [/Pulmonary alveolar proteinosis/],
    "Diverticulitis": [/Diverticulitis/],
    "GI obstruction": [/GI obstruction/],
    "Midgut volvulus": [/Midgut volvulus/],
    "Foreign body retained": [/Foreign body retained/],
    "Omphalocele or Gastroschisis": [/Omphalocele or Gastroschisis/],
    "Thyroiditis": [/Thyroiditis/],
    "Diverticulitis or abscess": [/Diverticulitis or abscess/],
    "Legg-Calve-Perthes disease": [/Legg-Calve-Perthes disease/],
    "Aspiration pneumonia": [/Aspiration pneumonia/],
    "Orchitis": [/Orchitis/],
    "Uterine anomalies": [/Uterine anomalies/],
    "Foreign body": [/Foreign body/],
    "Ewing sarcoma": [/Ewing sarcoma/],
    "Esophageal rupture": [/Esophageal rupture/],
    "Vascular ring anomalies": [/Vascular ring anomalies/],
    "Thyroid goiter or cancer": [/Thyroid goiter or cancer/],
    "Acute DVT": [/Acute DVT/],
    "Pyelonephritis": [/Pyelonephritis/],
    "Common AV canal": [/Common AV canal/],
    "Developmental dysplasia of the hip": [/Developmental dysplasia of the hip/],
    "Adnexal mass": [/Adnexal mass/],
    "Pulmonary sequestration": [/Pulmonary sequestration/],
    "Penetration or Aspiration": [/Penetration or Aspiration/],
    "Hydronephrosis with ureteral calculus": [/Hydronephrosis with ureteral calculus/],
    "Pneumonia all": [/Pneumonia all/],
    "Graves disease": [/Graves disease/],
    "Gastroparesis": [/Gastroparesis/],
    "Thymoma": [/Thymoma/],
    "Transposition of the great vessels": [/Transposition of the great vessels/],
    "PCP": [/PCP/],
    "Gastroesophageal reflux": [/Gastroesophageal reflux/],
    "Septic emboli": [/Septic emboli/],
    "Avascular necrosis": [/Avascular necrosis/],
    "Appendicitis": [/Appendicitis/],
    "Orbital fracture or muscle entrapment": [/Orbital fracture or muscle entrapment/],
    "Vesicoureteral reflux": [/Vesicoureteral reflux/],
    "Acute appendicitis": [/Acute appendicitis/],
    "Intersitial lung disease": [/Intersitial lung disease/],
    "Esophageal obstruction (partial)": [/Esophageal obstruction (partial)/],
    "Alzheimer's disease": [/Alzheimer's disease/],
    "Pathologic fracture": [/Pathologic fracture/],
    "Clubfoot": [/Clubfoot/],
    "Hirschsprung's disease": [/Hirschsprung's disease/],
    "Neuroblastoma": [/Neuroblastoma/],
    "Ileus": [/Ileus/],
    "Tuberculosis": [/Tuberculosis/],
    "Bronchiolitis": [/Bronchiolitis/],
    "Wrist fracture": [/Wrist fracture/],
    "Ascites or FAST": [/Ascites or FAST/],
    "Bronchopulmonary foregut malformations": [/Bronchopulmonary foregut malformations/],
    "Osteogenic sarcoma": [/Osteogenic sarcoma/],
    "Foreign body ingested": [/Foreign body ingested/],
    "Neuroendocrine tumor": [/Neuroendocrine tumor/],
    "Hydronephrosis": [/Hydronephrosis/],
    "Subdural or epidural hematoma": [/Subdural or epidural hematoma/],
    "Pneumothorax with or without tension": [/Pneumothorax with or without tension/],
    "Gallstones": [/Gallstones/],
    "GU malignancy": [/GU malignancy/],
    "GI malignancy": [/GI malignancy/],
    "Reflux": [/Reflux/],
    "Jejunal and ileal stenosis or atresia": [/Jejunal and ileal stenosis or atresia/],
    "Diffuse alveolar hemorrhage": [/Diffuse alveolar hemorrhage/],
    "CPAM": [/CPAM/],
    "Childhood fractures (Salter-Harris or torus)": [/Childhood fractures (Salter-Harris or torus)/],
    "Ovarian mass": [/Ovarian mass/],
    "Hydrocephalus": [/Hydrocephalus/],
    "Renal dysfunction": [/Renal dysfunction/],
    "Ankle fracture": [/Ankle fracture/],
    "Pancreas lesions": [/Pancreas lesions/],
    "Transplant kidney pathology": [/Transplant kidney pathology/],
    "Carotid stenosis": [/Carotid stenosis/],
    "Benign fibrous tumor of the pleura": [/Benign fibrous tumor of the pleura/],
    "Ectopic pregnancy": [/Ectopic pregnancy/],
    "Metastatic cancer": [/Metastatic cancer/],
    "Bladder leak": [/Bladder leak/],
    "Fibroids": [/Fibroids/],
    "LCH": [/LCH/],
    "Pelvic fracture": [/Pelvic fracture/],
    "UPJ obstruction": [/UPJ obstruction/],
    "Malrotation": [/Malrotation/],
    "Necrotizing enterocolitis": [/Necrotizing enterocolitis/],
    "Intussusception": [/Intussusception/],
    "Endometrial disease": [/Endometrial disease/],
    "Bone tumor": [/Bone tumor/],
    "DVT": [/DVT/],
    "Hypertrophic pyloric stenosis": [/Hypertrophic pyloric stenosis/],
    "Peritoneal disease": [/Peritoneal disease/],
    "Hepatoblastoma": [/Hepatoblastoma/],
    "Thyroid adenoma": [/Thyroid adenoma/],
    "Salter-Harris fracture": [/Salter-Harris fracture/],
    "Lines and umbilical catheters": [/Lines and umbilical catheters/],
    "Lymphoma or Leukemia": [/Lymphoma or Leukemia/],
    "Varicocele": [/Varicocele/],
    "Cholecystitis": [/Cholecystitis/],
    "ASD": [/ASD/],
    "Child abuse or Non-accidental trauma": [/Child abuse or Non-accidental trauma/],
    "PVL": [/PVL/],
    "Colitis": [/Colitis/],
    "Hip fracture": [/Hip fracture/],
    "Nephrolithiases": [/Nephrolithiases/],
    "Renal stone": [/Renal stone/],
    "Hiatal hernia": [/Hiatal hernia/],
    "Cerebral infarction": [/Cerebral infarction/],
    "Postop fracture evaluation": [/Postop fracture evaluation/],
    "Pneumonia": [/Pneumonia/],
    "Pulmonary edema": [/Pulmonary edema/],
    "Thyroid nodules": [/Thyroid nodules/],
    "Duodenal atresia": [/Duodenal atresia/],
    "Hypersensitivity pneumonitis": [/Hypersensitivity pneumonitis/],
    "PDA": [/PDA/],
    "Tethered cord": [/Tethered cord/],
    "Transient tachypnea of the newborn": [/Transient tachypnea of the newborn/],
    "Pancreatitis": [/Pancreatitis/],
    "VP shunt pseudocyst": [/VP shunt pseudocyst/],
    "Sarcoid": [/Sarcoid/],
    "Hydrocele": [/Hydrocele/],
    "Respiratory distress syndrome": [/Respiratory distress syndrome/],
    "SBO": [/SBO/],
    "Free intraperitoneal air": [/Free intraperitoneal air/],
    "Meconium aspiration": [/Meconium aspiration/],
    "Abscess": [/Abscess/],
    "Ureterocele": [/Ureterocele/],
    "Shoulder dislocation": [/Shoulder dislocation/],
    "Aspirated foreign body with air trapping": [/Aspirated foreign body with air trapping/],
    "Cervical spine fracture": [/Cervical spine fracture/],
    "Rhabdomyosarcoma": [/Rhabdomyosarcoma/],
    "Blocked or absent fallopian tube": [/Blocked or absent fallopian tube/],
    "TOF": [/TOF/],
    "Silicosis": [/Silicosis/],
    "Pneumoperitoneum": [/Pneumoperitoneum/],
    "Mesothelioma": [/Mesothelioma/],
    "Mediastinal masses": [/Mediastinal masses/],
    "Gallstone or Kidney stone": [/Gallstone or Kidney stone/],
    "Aortic dissection": [/Aortic dissection/],
    "SCFE": [/SCFE/],
    "Posterior urethral valves": [/Posterior urethral valves/],
    "Lymphoma": [/Lymphoma/],
    "TAPVR": [/TAPVR/],
    "Post-surgical leak GI": [/Post-surgical leak GI/],
    "Duplication of collecting systems": [/Duplication of collecting systems/],
    "Acute cholecystitis": [/Acute cholecystitis/],
    "Lung cancer primary or metastatic": [/Lung cancer primary or metastatic/],
    "Lymphangioleiomyomatosis": [/Lymphangioleiomyomatosis/],
    "Swallowed foreign body": [/Swallowed foreign body/],
    "Osteomyelitis": [/Osteomyelitis/],
    "Renal mass": [/Renal mass/],
    "Multisystic dysplastic kidney": [/Multisystic dysplastic kidney/],
    "Testicular neoplasms": [/Testicular neoplasms/],
    "Skeletal dysplasias": [/Skeletal dysplasias/],
    "Lymphadenitis": [/Lymphadenitis/],
    "Ovarian torsion": [/Ovarian torsion/],
    "Wilm's and other renal tumors": [/Wilm's and other renal tumors/],
    "Septic arthritis": [/Septic arthritis/],
    "VSD": [/VSD/],
    "Hardware complications": [/Hardware complications/],
    "Croup": [/Croup/],
    "Aortic aneurysm": [/Aortic aneurysm/]
};

exports.map = function(disease) {
    return diseaseToArrayML[disease] || [];
};

exports.keys = Object.keys(diseaseToArrayML);
